name: Smart CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Show Python Version
        run: python --version

      - name: Pipeline Running
        run: echo "Smart CI pipeline is active!"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Call ML Prediction API
        id: predict
        run: |
          response='{"failure_probability": 0.4}'
          echo "ML Response: $response"
          prob=$(echo $response | jq '.failure_probability')
          echo "failure_probability=$prob" >> $GITHUB_OUTPUT

      - name: Run Full Tests
        if: ${{ steps.predict.outputs.failure_probability > 0.6 }}
        run: echo "High risk commit → Running full tests"

      - name: Skip Heavy Tests
        if: ${{ steps.predict.outputs.failure_probability <= 0.6 }}
        run: echo "Low risk commit → Skipping heavy tests"
